#!/bin/bash
sudo apt-get install -y git
sudo apt-get install -y python
sudo apt-get install -y python-pip git-core
sudo apt-get install -y rabbitmq-server
sudo pip install pika==0.5.2
touch send.py
touch receive.py
chmod 700 install-script 
